# Imagen base de Python
FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos del directorio 'script' al contenedor
COPY requirements.txt requirements.txt
COPY script.py script.py

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Comando por defecto
CMD ["python", "script.py"]
