version: "3.9"
services:
  postgres:
    image: postgis/postgis:12-3.1  # Official PostGIS image based on PostgreSQL 12
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_postgis.sql:/docker-entrypoint-initdb.d/init_postgis.sql  # Mount init script here
    networks:
      - app_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - app_network

  python-script:
    build: .
    container_name: python-script
    depends_on:
      - postgres
    volumes:
      - ./script.py:/app/script.py
      - ./scriptbarrios.py:/app/scriptbarrios.py
      - ./scriptmetro.py:/app/scriptmetro.py
      - ./entrypoint.sh:/app/entrypoint.sh  # Script de entrada
    entrypoint: ["/bin/sh", "/app/entrypoint.sh"]  # Ejecutar el script de shell en el inicio
    networks:
      - app_network

  streamlit-app:
    build: .
    container_name: streamlit-app
    # Create a new entrypoint script for Streamlit
    volumes:
      - ./Bienvenido.py:/app/Bienvenido.py
      - ./pages:/app/pages
      - ./streamlit_entrypoint.sh:/app/streamlit_entrypoint.sh
    entrypoint: ["/bin/sh", "/app/streamlit_entrypoint.sh"]
    depends_on:
      - postgres
      - python-script  # Ensure python-script runs first
    ports:
      - "8501:8501"
    networks:
      - app_network
volumes:
  postgres_data:
    driver: local

networks:
  app_network:
    driver: bridge
