services:
  postgres:
    image: postgres:12.1
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  python-script:
    build:
      context: ./script  # Correct directory for the Dockerfile
    depends_on:
      - postgres
    environment:
      - WAIT_HOSTS=postgres:5432
    volumes:
      - ./script:/app  # Mount the 'script' folder correctly
    command: ["python", "script.py"]  # Ensure this matches the script name

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:

