version: "3.9"
services:
  postgres:
    image: postgis/postgis:12-3.1  # Official PostGIS image based on PostgreSQL 12
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init_postgis.sql:/docker-entrypoint-initdb.d/init_postgis.sql  # Mount init script here
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  python-script:
    build: .
    container_name: python-script
    depends_on:
      - postgres
    volumes:
      - ./script.py:/app/script.py
    entrypoint: ["python", "/app/script.py"]  # This ensures the script runs on container startup

volumes:
  postgres_data:
    driver: local
