FROM python:3.9-slim

WORKDIR /app

# Copy necessary files
COPY requirements.txt requirements.txt
COPY script.py script.py
COPY scriptbarrios.py scriptbarrios.py
COPY scriptmetro.py scriptmetro.py
COPY scriptcompras.py scriptcompras.py
COPY scriptalquileres.py scriptalquileres.py
COPY scriptprecios.py scriptprecios.py

# Copy the entrypoint script
COPY entrypoint.sh entrypoint.sh

# Create IdeaDatos directory and copy files
COPY IdeaDatos /app/IdeaDatos

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Make entrypoint script executable
RUN chmod +x entrypoint.sh

# Set default command
CMD ["/bin/sh", "/app/entrypoint.sh"]
