FROM python:3.9-slim

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios
COPY requirements.txt requirements.txt
COPY script.py script.py
COPY scriptbarrios.py scriptbarrios.py
COPY entrypoint.sh entrypoint.sh

# Instalar las dependencias
RUN pip install --no-cache-dir -r requirements.txt

# Hacer que el script de entrada sea ejecutable
RUN chmod +x entrypoint.sh

# Configurar el comando predeterminado para ejecutar el entrypoint
CMD ["/bin/sh", "/app/entrypoint.sh"]
